name: 'Quote Of The Day Action'
author: 'Victoria Lo'
description: 'Updates README with a quote of the day'
inputs:
  category:  # id of input
    description: 'Quote category to fetch'
    required: false
    default: 'inspire' 
    #possible values: inspire, management, sports, life, funny, love, art, students
  readme_path:
    description: 'Path of the readme file to update'
    default: "./README.md"
    required: false
runs:
  using: 'node12'
  main: 'index.js'
branding:
  icon: 'message-circle'
  color: 'white'
